Add --to <addr> option for `write` subcommand
soywod/himalaya pull request #361
Opened 2022-04-09 21:40 UTC by illfygli

Added this in my fork so that `himalaya write` can be used as a `mailto:`handler.

Happy to make any changes needed for merge if you think this addition makes sense.

2022-04-15 19:32 UTC, soywod commented
> Added this in my fork so that `himalaya write` can be used as a
> `mailto:`handler.

Thanks a lot for your contribution! I thought about this not so long
time ago and it is a very good addition.

> Happy to make any changes needed for merge if you think this addition
> makes sense.

I see that you added the `--to` arg, but in fact we could add other args
like `--cc`, `--subject` etc. Have a look at the `TplOverride` struct in
`tpl_args`, it does exactly this.

2022-04-15 23:38 UTC, illfygli commented
Thanks for the hint, I gave it a go. :)

2022-04-16 10:12 UTC, soywod requested changes
Sounds really great! I just have a last comment about dead code, and we can merge it.

2022-04-16 10:12 UTC, soywod commented on cli/src/msg/msg_entity.rs
> +    pub fn to(mut self, to: Vec<&str>) -> Result<Self> {
This function can be removed if it is not used any more.

2022-04-16 10:13 UTC, soywod commented
I also noticed that you targeted the wrong branch (`master`), I just switched it to `development`.

2022-04-16 11:39 UTC, illfygli commented
Now I discovered that it already works as a mailto-handler with just `himalaya` and no subcommand. :smile: 

But good to have this option as well, I think.

2022-04-16 11:50 UTC, soywod commented
> Now I discovered that it already works as a mailto-handler with just
> `himalaya` and no subcommand.

Ah yes indeed :) I realized that the mailto support is not documented at
all. I will update the README.

> But good to have this option as well, I think.

Yes anyway. Thanks a lot!

2022-04-16 11:50 UTC, merged