vim: msg_id is a string
soywod/himalaya pull request #383
Opened 2022-05-18 18:10 UTC by robertgzr

my msg_id's look like: b85, d39, ae0, etc.
and I get this error when using the vim plugin:

	Error: cannot find maildir message by short hash "0" at "/path/to/my/INBOX"
	Caused by:
	0: cannot find maildir message id from short hash "0"
	1: the short hash "0" matches more than one hash: 030598120934103c456ce08338886728, 06edb10a55efb89de45d8560aee33c8e

Signed-off-by: Robert Günzler <r@gnzler.io>

2022-05-21 09:29 UTC, soywod requested changes
Thanks a lot for you contribution! Indeed, Maildir message ids are UUID strings and the Vim plugin was not up-to-date. Did you try with a regular IMAP account to see if it is backward compatible? I just left one comment, we can merge straight after.

2022-05-21 09:29 UTC, soywod commented on vim/autoload/himalaya/msg.vim
> +  return matchstr(a:line, '[0-9a-z]*')
In fact it should be `[0-9a-fA-F]*`, see https://datatracker.ietf.org/doc/html/rfc4122#section-3.

2022-05-26 18:56 UTC, robertgzr commented
> Did you try with a regular IMAP account to see if your patch is backward compatible?

just did. works beautifully :)

2022-05-28 07:49 UTC, soywod approved these changes

2022-05-28 07:49 UTC, merged

2022-05-28 07:49 UTC, soywod commented
Thanks a lot :pray: