Make install script POSIX compliant
soywod/himalaya pull request #53
Opened 2021-04-05 03:10 UTC by vladimyr

Apart from being POSIX compliant this supports configuring install location through standard `PREFIX` environment variable, for example:
```sh
PREFIX="$HOME/.local" sh -c "$(curl -fsSL https://github.com/soywod/himalaya/raw/master/install.sh)"
```

2021-04-05 09:38 UTC, soywod requested changes
Thank you so much for the improvement!! I just have some questions (I put them in a review).

2021-04-05 09:38 UTC, soywod commented on README.md
> +sh -c "$(curl -sSL https://github.com/soywod/himalaya/raw/master/install.sh)"
Why replacing `raw.githubusercontent.com` by `github.com`? In fact the cURL command can be simplified by `curl -sS https://raw.githubusercontent.com/soywod/himalaya/master/install.sh`, it prevents a redirection.

2021-04-05 09:38 UTC, soywod commented on install.sh
> +    windows) system="windows" ;;
`uname_os` and `get_system` cannot be merged together?

```suggestion
    msys*) os="windows" ;;
    mingw*) os="windows" ;;
    cygwin*) os="windows" ;;
    win*) os="windows" ;;
```

2021-04-05 09:38 UTC, soywod commented on install.sh
> +start
What's the benefit of wrapping everything in a `start` function?

2021-04-06 12:25 UTC, chambln commented
Sorry for the suggestions spam.  A lot of this is redundant assignments passing values around.  The gist of the program is as follows:

1. Detect OS by matching `uname -s | tr [:upper:] [:lower:]` against known values and exit nonzero if unrecognised
2. Download the corresponding release archive using curl(1)
3. Extract the archive using tar(1)
4. Copy `himalaya.exe` to `/usr/local/bin/himalaya` and make it executable
5. Clean up any temporary files upon exit using trap(1)

There may be more robust ways of doing OS detection in a POSIX friendly way, but uname(1) might be enough (what's the uname output on Windows systems?).  Could steal some some ideas from <https://github.com/dylanaraps/pfetch>.

Step 4 should probably be done as root.  Can we call it a POSIX shell script if it makes calls to sudo?  It may be better to suggest the user pipes the whole script into `sudo sh` than have sudo commands in the script.  Then the user could substitute sudo(1) for doas(1) or su(1) without having to edit the script.

2021-04-06 13:15 UTC, soywod commented on install.sh
> +start
If the only benefits are for testing purposes then we can forget! I don't plan to test the `install.sh` :laughing: (except for the OS detection there is no logic). So I would remove it. [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

2021-04-06 13:19 UTC, soywod commented on install.sh
> +  if ! tmpdir=$(mktemp -d); then
I don't mind if it's not POSIX, at least it's better than what we got before (I think). Feel free to propose any better alternative!

2021-04-06 13:22 UTC, soywod commented on install.sh
> +}
It's way more concise this way, I approve also!

2021-04-06 16:30 UTC, chambln commented on install.sh
> +  if ! tmpdir=$(mktemp -d); then
```sh
trap 'rm -f /tmp/himalaya.tar.gz /tmp/himalaya.exe' EXIT
mkdir -p /tmp
...
```

2021-04-11 22:55 UTC, soywod commented
@vladimyr what do you think about @chambln propositions?

2021-04-15 13:26 UTC, soywod commented
@chambln I did all the changes you proposed. Could you check one more time before I merge?

2021-04-16 07:13 UTC, vladimyr commented
Sorry for being unresponsive, I've had limited FOSS time for the last few days. Anyway if you are still interested I'll gladly go through your questions and explain the rationale behind my choices.

2021-04-16 08:13 UTC, soywod commented
@vladimyr I am sorry, I took the initiative to push commits on your branch to merge faster. Even if the discussion is not terminated with @chambln, the result is still better than what we got before :smiley:

> Anyway if you are still interested I'll gladly go through your questions and explain the rationale behind my choices.

With great pleasure! Thanks for you contribution anyway.

2021-04-16 08:14 UTC, merged

2021-04-18 02:40 UTC, chambln commented
Looks much better already!

If POSIX compliance is the goal then sudo must not be used in the script. I think it's wise to leave privilege elevation to the person running the script anyway. We can still *suggest* using sudo in `README.md`, i.e.

```sh
curl ... | sudo sh
```