Respect smtp port when sending email
soywod/himalaya pull request #94
Opened 2021-04-13 05:11 UTC by srid

Fixes #87

2021-04-13 06:34 UTC, soywod requested changes

2021-04-13 06:34 UTC, soywod commented on src/smtp.rs
> +    let builder = smtp_relay(&account.smtp_host)?;
Is this intermediate variable necessary?

2021-04-13 06:34 UTC, soywod commented on src/smtp.rs
>          .timeout(Some(Duration::new(1000, 0)))
Can you also remove this line since it was to debug the timedout issue?

2021-04-13 14:44 UTC, merged

2021-04-13 14:44 UTC, soywod commented
Thanks a lot for all your contributions :heart:

2021-04-14 13:42 UTC, AckslD commented
Thanks @srid! This also solved it for me, i.e. #60